<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260930132813 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema: tracked_repositories, contributors, commits';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE commits (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sha VARCHAR(40) NOT NULL, author_name VARCHAR(255) NOT NULL, author_email VARCHAR(320) DEFAULT NULL, message TEXT NOT NULL, committed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, html_url VARCHAR(512) NOT NULL, repository_id INT NOT NULL, contributor_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_commit_committed_at ON commits (committed_at)');
        $this->addSql('CREATE INDEX idx_commit_repo_contributor ON commits (repository_id, contributor_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_commit_repo_sha ON commits (repository_id, sha)');
        $this->addSql('CREATE INDEX IDX_B327C47050C9D4F7 ON commits (repository_id)');
        $this->addSql('CREATE INDEX IDX_B327C4707A19A357 ON commits (contributor_id)');
        $this->addSql('CREATE TABLE contributors (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, identity VARCHAR(320) NOT NULL, email VARCHAR(320) DEFAULT NULL, display_name VARCHAR(255) NOT NULL, avatar_url VARCHAR(512) DEFAULT NULL, first_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_contributor_identity ON contributors (identity)');
        $this->addSql('CREATE TABLE tracked_repositories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(32) NOT NULL, owner VARCHAR(100) NOT NULL, name VARCHAR(100) NOT NULL, last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, sync_status VARCHAR(16) NOT NULL, last_sync_error TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_repo_provider_owner_name ON tracked_repositories (provider, owner, name)');
        $this->addSql('ALTER TABLE commits ADD CONSTRAINT FK_B327C47050C9D4F7 FOREIGN KEY (repository_id) REFERENCES tracked_repositories (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commits ADD CONSTRAINT FK_B327C4707A19A357 FOREIGN KEY (contributor_id) REFERENCES contributors (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE commits DROP CONSTRAINT FK_B327C47050C9D4F7');
        $this->addSql('ALTER TABLE commits DROP CONSTRAINT FK_B327C4707A19A357');
        $this->addSql('DROP TABLE commits');
        $this->addSql('DROP TABLE contributors');
        $this->addSql('DROP TABLE tracked_repositories');
    }
}
